---
title: "Leitprogramm: Verhaltensbiologie"
site: bookdown::bookdown_site
github-repo: "samueltobler/verhaltensbiologie"
documentclass: book
link-citations: yes
description: |
  Diese digitale Leitprogramm behandelt die Grundkonzepte der Verhaltensbiologie 
  auf gymnasialer Ebene. 
---

# Einleitung {.unnumbered}

Diese digitale Unterrichtseinheit dient als Einführung in das Thema Verhaltensbiologie. Sie ist als Leitprogramm aufgebaut, das Ihnen ermöglicht, selbstständig und in Ihrem eigenen Tempo an den Inhalten zu arbeiten.



### Was ist ein Leitprogramm und wie funktioniert es? {.unnumbered}

Ein Leitprogramm ist eine strukturierte Lernanleitung, mit der Sie ein Thema selbstständig und schrittweise erarbeiten können. Es führt Sie gezielt durch Lernziele, Arbeitsaufträge und passende Materialien. Zu Beginn erhalten Sie eine Einführung, in der Ziele und Inhalte erläutert werden. Anschliessend bearbeiten Sie systematisch die Arbeitsaufträge und nutzen unterstützende Materialien wie Texte, Grafiken oder Videos. Ihren Lernfortschritt überprüfen Sie regelmässig durch Kontrollfragen (Mastery Checks) oder Übungen.

### Aufgabenstellungen {.unnumbered}

Die Aufgaben sind mit unterschiedlichen Symbolen gekennzeichnet, die Ihnen helfen, den Schwierigkeitsgrad der jeweiligen Aufgabe einzuschätzen. Ein leerer Kreis (○) signalisiert, dass sich die Frage auf das im Kapitel erarbeitete Wissen bezieht. Ein halb gefüllter Kreis (◑) bedeutet, dass ein vertieftes Verständnis des Themas notwendig ist, um die Frage beantworten zu können. Ein ausgefüllter Kreis (●) zeigt an, dass das Wissen in einem neuen Kontext angewendet werden muss. Dieser Fragetyp stellt somit die grösste Herausforderung dar. Am Ende jedes Kapitels finden Sie zudem einen Mastery Check zur Überprüfung Ihres Lernfortschritts.

### Wie kann ich meinen Lernfortschritt speichern? {.unnumbered}

Damit Sie später auf Ihre Notizen und Antworten zu den Fragen zurückgreifen können, sollten Sie ein separates Dokument in einem Programm wie Microsoft Word oder Google Docs erstellen, um Ihre Resultate und Überlegungen festzuhalten.

Falls Sie über ein Google-Konto verfügen, können Sie direkt das Vorlagen-Dokument zur Notizerfassung verwenden. Den Link dazu finden Sie weiter unten. Um es zu nutzen, melden Sie sich in Ihrem Google-Konto an, klicken in der oberen Leiste auf «Datei» und wählen anschliessend «Kopie erstellen». Alternativ können Sie das Dokument auch als Word-Datei herunterladen und lokal bearbeiten.



<a href="http://bit.ly/4kldyCp" download style="
  display: inline-block;
  padding: 10px 20px;
  font-size: 16px;
  background-color: #404f58;
  color: white;
  border-radius: 5px;
  text-decoration: none;
">
→ Vorlagen-Dokument
</a>



### Technische Voraussetzungen {.unnumbered}

Zur Bearbeitung dieser Unterrichtsmaterialien mithilfe der digitalen Unterrichtseinheit benötigen Sie ein internetfähiges Gerät. Damit alle Inhalte richtig dargestellt werden, ist ein Gerät mit mind. 10 Zoll empfohlen. 

<br>

#### Viel Vergnügen bei der Erarbeitung des Themas! {.unnumbered}


